import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  cameraFill: { ...StyleSheet.absoluteFillObject },
  headText: {
    color: 'white',
    fontSize: 20,
    textAlign: 'center',
    marginTop: 50,
    fontWeight: '600',
  },
  scannContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  instructionWrapper: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#fff',
    borderRadius: 30,
    marginBottom: 20,
    zIndex: 2,
    alignSelf: 'center',
  },
  instructionText: { color: '#fff', fontSize: 13 },
  scanBox: {
    width: 250,
    height: 250,
    borderColor: '#fff',
    borderWidth: 2,
    borderRadius: 0,
    zIndex: 1,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tapText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  closeBtn: {
    position: 'absolute',
    bottom: 60,
    alignSelf: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: 'white',
    borderRadius: 70,
    zIndex: 2,
  },
  closeText: { fontSize: 24, color: 'white' },
});
